travis:
  secure:
    BINSTAR_TOKEN: dqHFf6xJUCtHEYKG9DJjuGXGozA/IK/Hww8R5A1SJFtB3fn7hPGnO2+VWqShgR1/lTUJYVlvF73fI1fXnk83yQSVe4kdRFsDbQx9JC7ZJba+1YqoF0BYoWHLaYZrci95Nu0YiosnOROOn1GB/T+USlvrNRQCZwCUobx8VAMqA2iREv9ppub5A5EgHQV6DHrzTIslQNtpr8YRIahFZMcqu4Lwc4/MBBbsacHlFE0km5iU1iZsatoWWTjX2axaQInRIo6plc5JdzofplzLJx1ttrY4XTJCcET9Ljo5qBU09qcNcFP2WsznrLDSHroD9iEPRxQPtelJa0xhAFwXY7V7ivDmwQzv2AXMZoaJF8J7geILkMU+xgzsAKVpiDXRRDXFZIBZLQL3ejCPjLk/T/tLCTdkDcwt5+1urLpeiwRkGpLb2s1l9wvul7fDNGKuJ82hoLHkul79pEqw3KJnie14ix+t9DUOG4XFqoBDlsVg1IkJB2hZLcu9C951dDnyReiJ6uwuJ8RNlf/rug1qtase4A9OtOSarovDPGmaxXB84/0Mk/4mS7KuiutB/Ix7nHOr1DP9s/eR6ExlFJVD/CSlrESL2Bepq4uhk0qTdwSzkCMaOEMkT/Q4pfIOEH2X+RPJ05yntwK0KMfV7V93n5GAlOW/Jgkknh8/xtFwkC9PVTA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
